Dot product

In [2]:
import numpy as np

a · b = (1×4) + (2×5) + (3×6)
      = 4 + 10 + 18
      = 32

In [ ]:

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.dot(a, b)
print(result)  

32


Multiplication

A = [1 2]   [3 4]          

B = [5 6]   [7 8]   


C[0,0] = (1×5)+(2×7) = 19
C[0,1] = (1×6)+(2×8) = 22
C[1,0] = (3×5)+(4×7) = 43
C[1,1] = (3×6)+(4×8) = 50

C = [19 22]   [43 50]



In [3]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

C = A @ B
print(C)


[[19 22]
 [43 50]]


Identity 
I = [1 0][0 1]

In [ ]:


I = np.eye(2)
print(I)

print(A @ I) 

[[1. 0.]
 [0. 1.]]
[[1. 2.]
 [3. 4.]]


Transpose

A = [1 2][3 4]   
    
Aᵗ = [1 3][2 4]

In [6]:
print(A.T)


[[1 3]
 [2 4]]


Inverse 

A⁻¹ = 1/(ad - bc) × [ d -b] [-c  a]

det(A) = (1×4) - (2×3) = 4 - 6 = -2

A⁻¹ = 1/(-2) × [ 4 -2][-3  1]

= [-2    1 ][1.5  -0.5]

In [14]:
A = np.array([[1, 2],[3, 4]])

a_inv = np.linalg.inv(A)
print(a_inv)


[[-2.   1. ]
 [ 1.5 -0.5]]


In [18]:
# Sanity check: A @ A_inv should ≈ identity
print(A @ a_inv)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


# Reflection

## What I Learned

- Implemented dot product from scratch.
- Implemented matrix multiplication from scratch.
- Verified results using NumPy.
- Understood identity, transpose and inverse matrices.
- Learned geometric interpretation of vectors and matrices.

## Challenges

- Understanding matrix multiplication indexing.
- Visualizing transformations.

## Improvements

- Better understanding of NumPy linear algebra.
- Improved confidence in implementing mathematical operations manually.

## Next Steps

- Learn eigenvalues and eigenvectors.
- Explore machine learning applications of linear algebra.