#importing the numpy and performong the basic operation 

In [1]:
import numpy as np

In [16]:
a = np.array((1,2,3,4,5))
print(a);

[1 2 3 4 5]


In [9]:
b = np.array((6,7,8,9,10))
print(b);

[ 6  7  8  9 10]


In [10]:
print (a+b)

[ 7  9 11 13 15]


In [15]:
a = np.array([1, 2, 3, 4, 5],np.int32)
print(a[2])

3


In [37]:
f = np.array([[13,2,34,45,5]],)

f[0]



array([13,  2, 34, 45,  5])

In [41]:
f = np.array([[13,2,34,45,5]],np.int64)

d=f[0, 3]
print(d)

45


In [56]:
c = np.array([3,1,5,3,7,3,6,1])
c.shape


(8,)

In [60]:
c = np.array([[3,1,5],[4,6,2]])
c.shape


(2, 3)

In [61]:
c.size

6

In [62]:
c.dtype

dtype('int64')

In [65]:
c[1,1]=25

print(c)

[[ 3  1  5]
 [ 4 25  2]]


In [66]:
zeros = np.zeros((3,4))

In [67]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [71]:
rng = np.arange(14)
print(rng)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]


In [75]:
l = np.linspace(1,10,5)
print(l)

[ 1.    3.25  5.5   7.75 10.  ]


In [79]:
i = np.identity(5)
print(i)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


axis in nu pumpy


In [81]:
arr = np.array([[3,4,5],[1,4,9],[4,8,6]])

In [83]:
arr

array([[3, 4, 5],
       [1, 4, 9],
       [4, 8, 6]])

In [84]:
 arr.sum(axis=0)

array([ 8, 16, 20])

In [85]:
arr.sum(axis=1)

array([12, 14, 18])

In [87]:
arr.T

array([[3, 1, 4],
       [4, 4, 8],
       [5, 9, 6]])

In [88]:
arr.flat

In [91]:
for item in arr.flat:
    print(item)

3
4
5
1
4
9
4
8
6


In [92]:
arr.ndim

2

In [93]:
arr.size

9

In [94]:
arr.shape

(3, 3)

In [95]:
arr.dtype

dtype('int64')

In [96]:
arr.nbytes

72

In [101]:
ar = np.array([3, 4, 5, 40, 6])
ar.argmax()

np.int64(3)

In [102]:
ar = np.array([3, 4, 5, 40, 6])
ar.argmin()

np.int64(0)

In [107]:
ar = np.array([3, 4, 5, 40, 6])
ar.argsort()

array([0, 1, 2, 4, 3])

In [110]:
print(arr)

[[3 4 5]
 [1 4 9]
 [4 8 6]]


In [112]:
arr.argmax(axis=0)

array([2, 2, 1])

In [113]:
arr.argmax(axis=1)

array([2, 2, 1])

In [114]:
arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 2, 1]])

In [115]:
arr.argsort(axis=0)

array([[1, 0, 0],
       [0, 1, 2],
       [2, 2, 1]])

In [116]:
np.sqrt(arr)

array([[1.73205081, 2.        , 2.23606798],
       [1.        , 2.        , 3.        ],
       [2.        , 2.82842712, 2.44948974]])

In [118]:
b = print(arr+4)

[[ 7  8  9]
 [ 5  8 13]
 [ 8 12 10]]
