In [1]:
import numpy as np 

Exercise 1 

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
zeros = np.zeros(3)
print(zeros)

[0. 0. 0.]


In [5]:
ones = np.ones(5)
print(ones)

[1. 1. 1. 1. 1.]


In [6]:
num = np.arange(1,11)
print(num)

[ 1  2  3  4  5  6  7  8  9 10]


Exercise 2

In [7]:
arr = np.arange(12)

matrix = arr.reshape(3, 4)

print(matrix)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Exercise 3

In [12]:
arr = np.arange(12).reshape(3,4)

print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

(3, 4)
12
int64
2


In [18]:
arr = np.arange(10)

print(arr[2:7])
print(arr[:7])
print(arr[2:])
print(arr[-3:])

[2 3 4 5 6]
[0 1 2 3 4 5 6]
[2 3 4 5 6 7 8 9]
[7 8 9]


In [23]:
arr = np.arange(16).reshape(4,4)

print(arr) 
print(matrix[1])
print(matrix[:2])
print(matrix[:,2])
print(matrix[1:3,1:3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[ 2  6 10]
[[ 5  6]
 [ 9 10]]


boolean mask 

In [27]:
arr = np.arange(10)
mask = arr > 5
print(mask)
print(arr[mask])

[False False False False False False  True  True  True  True]
[6 7 8 9]


Multiple condition 

In [32]:
arr = np.arange(20)
result = (arr > 5) & (arr < 15)
result2 = arr[(arr > 5) & (arr < 15)]
print(result)
print(result2)

[False False False False False False  True  True  True  True  True  True
  True  True  True False False False False False]
[ 6  7  8  9 10 11 12 13 14]


Axis aggregation

In [33]:
matrix = np.arange(12).reshape(3,4)

print(matrix.sum())

print(matrix.sum(axis=0))

print(matrix.sum(axis=1))

66
[12 15 18 21]
[ 6 22 38]


Statistics

In [34]:
arr = np.array([5,10,15,20,25])

print(np.mean(arr))
print(np.median(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))


15.0
15.0
25
5
7.0710678118654755


Broadcasting

In [35]:
arr = np.array([1,2,3,4])

result = arr + 10

print(result)

[11 12 13 14]


Broadcasting with matrix


In [36]:
matrix = np.array([
    [1,2,3],
    [4,5,6]
])

vector = np.array([10,20,30])

result = matrix + vector

print(result)

[[11 22 33]
 [14 25 36]]


Element-wise operations

In [37]:
a = np.array([1,2,3])

b = np.array([4,5,6])

print(a+b)

print(a*b)

print(a**2)

print(np.sqrt(a))

[5 7 9]
[ 4 10 18]
[1 4 9]
[1.         1.41421356 1.73205081]


Python loop version

In [38]:
numbers = list(range(1000000))

squared = []

for n in numbers:
    squared.append(n * n)

numpy version

In [40]:
arr = np.arange(1000000)

squared = arr * arr

## Benchmark Note

I compared squaring one million numbers using a Python loop and a NumPy vectorized operation.

The Python loop took significantly longer because each iteration is executed individually by the Python interpreter.

The NumPy solution performed the operation on the entire array at once using optimized C-level implementations.

The vectorized NumPy operation was approximately 30–50 times faster on my machine.

This demonstrates why NumPy is preferred for numerical computing and large-scale data processing.


# Reflection

In this exercise, I learned the fundamentals of NumPy and how it differs from working with standard Python lists. I practiced creating arrays, reshaping data, and using slicing techniques to access specific elements efficiently.

I also learned how boolean masking can be used to filter data without writing loops, making the code cleaner and easier to read. Understanding axis operations helped me perform calculations across rows and columns, while broadcasting demonstrated how NumPy can automatically apply operations across arrays of different shapes.

The benchmark comparison between a Python loop and a vectorized NumPy operation showed that NumPy is significantly faster for numerical computations. This is because NumPy performs operations using optimized low-level implementations instead of processing elements one by one in Python.

Overall, this exercise helped me understand the importance of vectorization, broadcasting, and efficient array operations. These concepts will be valuable when working with data analysis, machine learning, and scientific computing tasks in the future.
