Import numpy

In [1]:
import numpy as np

Dataset 

In [2]:
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

y = np.array([[0], [1], [1], [1]])

Weights and bias

In [3]:
np.random.seed(42)

weights = np.random.randn(2, 1)
bias = np.random.randn(1)

print("Weights:\n", weights)
print("Bias:", bias)

Weights:
 [[ 0.49671415]
 [-0.1382643 ]]
Bias: [0.64768854]


Implement sigmoid 


In [4]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

y=\frac{1}{1+e^{-x}}

In [5]:
z = np.dot(X, weights) + bias
y_pred = sigmoid(z)

print("Predictions:")
print(y_pred)

Predictions:
[[0.65648939]
 [0.62467149]
 [0.75848706]
 [0.73226375]]


Mean sq error

In [6]:
loss = np.mean((y - y_pred) ** 2)

print("Loss:", loss)

Loss: 0.17546525262263657


Compute gradient 

In [7]:
sigmoid_derivative = y_pred * (1 - y_pred)

In [8]:
dL_dy = -2 * (y - y_pred) / len(y)

In [9]:
delta = dL_dy * sigmoid_derivative

In [11]:
dw = np.dot(X.T, delta)

In [12]:
db = np.sum(delta)

In [13]:
print("Gradient Weights:\n", dw)
print("Gradient Bias:", db)

Gradient Weights:
 [[-0.04836603]
 [-0.07024452]]
Gradient Bias: -0.01834241677719908


Perform gradient 

In [14]:
learning_rate = 0.5

In [15]:
weights -= learning_rate * dw
bias -= learning_rate * db

In [16]:
print("Updated Weights:\n", weights)
print("Updated Bias:", bias)

Updated Weights:
 [[ 0.52089717]
 [-0.10314204]]
Updated Bias: [0.65685975]


Forward pass again 

In [17]:
z = np.dot(X, weights) + bias
y_pred_new = sigmoid(z)

new_loss = np.mean((y - y_pred_new) ** 2)

print("New Predictions:")
print(y_pred_new)

print("New Loss:", new_loss)

New Predictions:
[[0.65855462]
 [0.6349977 ]
 [0.76454425]
 [0.74547355]]
New Loss: 0.1717859991541573


Train for 1000 epochs

In [18]:
epochs = 1000

for epoch in range(epochs):

    z = np.dot(X, weights) + bias
    y_pred = sigmoid(z)

    loss = np.mean((y - y_pred) ** 2)

    dL_dy = -2 * (y - y_pred) / len(y)
    delta = dL_dy * y_pred * (1 - y_pred)

    dw = np.dot(X.T, delta)
    db = np.sum(delta)

    weights -= learning_rate * dw
    bias -= learning_rate * db

    if epoch % 100 == 0:
        print(f"Epoch {epoch}: Loss = {loss:.4f}")

Epoch 0: Loss = 0.1718
Epoch 100: Loss = 0.0709
Epoch 200: Loss = 0.0392
Epoch 300: Loss = 0.0257
Epoch 400: Loss = 0.0186
Epoch 500: Loss = 0.0144
Epoch 600: Loss = 0.0117
Epoch 700: Loss = 0.0098
Epoch 800: Loss = 0.0084
Epoch 900: Loss = 0.0073


Final Prediction 

In [19]:
predictions = sigmoid(np.dot(X, weights) + bias)

print(predictions)

[[0.12131404]
 [0.92551929]
 [0.92563162]
 [0.99910814]]


In [20]:
binary_predictions = (predictions >= 0.5).astype(int)

print(binary_predictions)

[[0]
 [1]
 [1]
 [1]]
