In [1]:
import torch


In [2]:
torch.rand(2,2)


tensor([[0.0520, 0.7167],
        [0.1407, 0.0082]])

1D

In [3]:
x=torch.empty(4)
print(x)

tensor([0., 0., 0., 0.])


2D

In [4]:
x=torch.empty(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


3D

In [5]:
x=torch.empty(2,2,3)
print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


4D

In [6]:
torch.empty(3,2,2,4)

tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]]]])

zeros 

In [7]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

onees

In [8]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
x.size()

torch.Size([2, 2, 3])

In [11]:
x=torch.ones(3,3, dtype=torch.int)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [13]:
torch.tensor([4.0,3.0,6,1])

tensor([4., 3., 6., 1.])

In [16]:
torch.manual_seed(42)
x=torch.rand(2,2)
y=torch.rand(2,2)
print(x)
print(y)




tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])
tensor([[0.3904, 0.6009],
        [0.2566, 0.7936]])


In [19]:
z=x+y
print(z)

tensor([[1.2727, 1.5159],
        [0.6394, 1.7529]])


direct using the function 

In [20]:
torch.add(x,y)

tensor([[1.2727, 1.5159],
        [0.6394, 1.7529]])

In [21]:
z=x-y
print(z)

tensor([[0.4918, 0.3141],
        [0.1263, 0.1657]])


Direct using function 

In [23]:
torch.sub(x,y)

tensor([[0.4918, 0.3141],
        [0.1263, 0.1657]])

Multiply

In [24]:
torch.mul(x,y)

tensor([[0.3445, 0.5498],
        [0.0982, 0.7613]])

In [26]:
x=torch.rand(2,2)
y=torch.rand(2,2)
print(x)
print(y)

tensor([[0.8694, 0.5677],
        [0.7411, 0.4294]])
tensor([[0.8854, 0.5739],
        [0.2666, 0.6274]])


In [27]:
y.add_(x)

tensor([[1.7548, 1.1416],
        [1.0077, 1.0569]])

In [28]:
z=x+y
print(z)

tensor([[2.6243, 1.7093],
        [1.7488, 1.4863]])


In [29]:
x=torch.rand(5,3)
print(x)


tensor([[0.2696, 0.4414, 0.2969],
        [0.8317, 0.1053, 0.2695],
        [0.3588, 0.1994, 0.5472],
        [0.0062, 0.9516, 0.0753],
        [0.8860, 0.5832, 0.3376]])


data of 2nd row

In [34]:
x[:,1]

tensor([0.4414, 0.1053, 0.1994, 0.9516, 0.5832])

data of 3rd row

In [33]:
x[:,2]

tensor([0.2969, 0.2695, 0.5472, 0.0753, 0.3376])

In [37]:
x=torch.rand(4,4)
print(x)
x.view(16)

tensor([[0.2036, 0.2018, 0.2018, 0.9497],
        [0.6666, 0.9811, 0.0874, 0.0041],
        [0.1088, 0.1637, 0.7025, 0.6790],
        [0.9155, 0.2418, 0.1591, 0.7653]])


tensor([0.2036, 0.2018, 0.2018, 0.9497, 0.6666, 0.9811, 0.0874, 0.0041, 0.1088,
        0.1637, 0.7025, 0.6790, 0.9155, 0.2418, 0.1591, 0.7653])

In [40]:
x.view(2,2,4)

tensor([[[0.2036, 0.2018, 0.2018, 0.9497],
         [0.6666, 0.9811, 0.0874, 0.0041]],

        [[0.1088, 0.1637, 0.7025, 0.6790],
         [0.9155, 0.2418, 0.1591, 0.7653]]])

convert tensor to numpy

In [44]:
a=torch.ones(6)
print(a)
print(type(a))
b=a.numpy()
print(b)    
print(type(b))

tensor([1., 1., 1., 1., 1., 1.])
<class 'torch.Tensor'>
[1. 1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [ ]:
a.add_(3)
print(a)


tensor([4., 4., 4., 4., 4., 4.])


as numpy and the tensor point to same variable 

In [46]:
print(b)

[4. 4. 4. 4. 4. 4.]


convert numpy to tensor 

In [47]:
import numpy as np
a=np.ones(5)
print(a)
print(type(a))
b=torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [50]:
a+=2
print(a)

[7. 7. 7. 7. 7.]


In [51]:
print(b)

tensor([7., 7., 7., 7., 7.], dtype=torch.float64)


backpropagation

In [54]:
 x=torch.tensor(4.,requires_grad=True)
 print(x)

tensor(4., requires_grad=True)


In [55]:
y=x**3
print(y)

tensor(64., grad_fn=<PowBackward0>)


In [56]:
y.backward()
print(x.grad)

tensor(48.)


In [57]:
l1=[[2.,3.,5.],[6.,5.,11.],[13.,17.,18]]
x=torch.tensor(l1,requires_grad=True)
print(x)

tensor([[ 2.,  3.,  5.],
        [ 6.,  5., 11.],
        [13., 17., 18.]], requires_grad=True)


In [58]:
y=x**3+x**2
print(y)


tensor([[  12.,   36.,  150.],
        [ 252.,  150., 1452.],
        [2366., 5202., 6156.]], grad_fn=<AddBackward0>)


dy/dx=3x^2+2x

In [60]:
z=y.sum()
print(z)

tensor(15776., grad_fn=<SumBackward0>)


In [61]:
z.backward()

In [62]:
print(x.grad)

tensor([[  16.,   33.,   85.],
        [ 120.,   85.,  385.],
        [ 533.,  901., 1008.]])
